version: '3.5'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: BackendDockerfile
    depends_on:
      - redis
      - postgres
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=boban_jones
      - POSTGRES_DATABASE=postgres
      - REQUEST_ORIGIN=http://localhost:80

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: FrontendDockerfile
    depends_on:
      - backend
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:80

  redis:
    container_name: redis
    image: redis
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: boban_jones

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
