version: '3.5'

services:
  backend:
    container_name: 3.6-backend
    build: 
      context: .
      dockerfile: BackendDockerfile
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost:80

  nginx:
    container_name: 3.6-frontend
    build:
      context: .
      dockerfile: FrontendDockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/usr/share/nginx/nginx.conf
