version: '3.5'

services:
  frontend:
    build: 
      context: .
      dockerfile: FrontendDockerfile
    ports:
      - 5000:5000

  backend:
    build:
      context: .
      dockerfile: BackendDockerfile
    ports:
      - 8080:8080
